# Generated by Django 5.1.5 on 2025-01-15 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring_app.fooditem')),
                ('user_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring_app.userlog')),
            ],
        ),
        migrations.AddField(
            model_name='userlog',
            name='food_items',
            field=models.ManyToManyField(through='monitoring_app.FoodConsumption', to='monitoring_app.fooditem'),
        ),
    ]
