# Generated by Django 5.1.4 on 2025-02-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0004_mealplan_mealitem_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('calories_consumed', models.IntegerField(blank=True, null=True)),
                ('workout_intensity', models.CharField(blank=True, max_length=50, null=True)),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('mood', models.CharField(blank=True, max_length=50, null=True)),
                ('food_items', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
